<a href="https://colab.research.google.com/github/UnaSun2025/MSSP6070/blob/main/WeeklyModules/Week04/Participation%20Activity%20Week%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Another way yo upload files:

In [ ]:
from google.colab import files  #I put this into a Python file called Google_connection and copied it to my Google Drivce

uploaded = files.upload()

for fn in uploaded.keys(): #fn:function
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

In [ ]:
# I ran the Google_Connection Python file to connect Google Drive and upload data
# as an alternative to retying the connection code above.

runfile('/content/drive/MyDrive/MSSP607/CodeSamples/Google_Connection.py') # I can run the Google_Connection Python file to connect Google Drive and upload data

In [3]:
project_path = '/content/drive/My Drive/MSSP607'

In [4]:
df = pd.read_csv(project_path + '/parsed.csv')
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url', 'parsed_place'],
      dtype='object')

2. Complete the following exercise:

a. Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'

In [5]:
Japan_mb = df[(df['place'].str.contains('Japan'))&(df['magType'] == 'mb')]
percentile_95 = Japan_mb['mag'].quantile(0.95)
print(percentile_95)

4.9

or coding:

In [6]:
results = df[(df.parsed_place.str.endswith('Japan')) & (df.magType == 'mb')]
results
#Using tab completion we can get the column names
results.columns
results[['parsed_place', 'mag']]
#One solution is to import Numpy and use its percentile method to caluclate the 95%
#Remember, we filtered the original dataframe to get the 'results' dataframe, then sent the 'mag' sequence to the Numpy method
import numpy as np
percentile_95 = np.percentile(results.mag,95) #Select the 'mag' series.
print('The 95th percentile of earthquakes in Japan is',percentile_95)

#or coding in a different library
#You may recall that in the first week of class, we reviewed the Introduction_to_data_analysis Notebook.
#In that Notebook, there is an example of calculating quintiles.
#For this example, you can reference https://docs.python.org/3/library/statistics.html?highlight=quartiles#statistics.quantiles
#We need to filter the original dataframe to select the instances that meet the criteria

#Alternatively, we can use Pandas' methods to calcualte the 95%, but we neet to fileter the original dataframe.
#Here we work from inside the '()' outward to build an object where we can use the quantile method on the mag series(column).
print('The 95th percentile of earthquakes in Japan is',df[(df.parsed_place.str.endswith('Japan')) & (df.magType == 'mb')].mag.quantile(0.95))

The 95th percentile of earthquakes in Japan is 4.9

b. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.

In [7]:
Indonesia = df[df['place'].str.contains('Indonesia')]
pct_tsunamis = (Indonesia['tsunami'].sum()/len(Indonesia))*100
print(pct_tsunamis)

or coding:

In [8]:
df[df.parsed_place.str.endswith('Indonesia')].describe()
#
#Using the f-strings as a way to format strings:

f"""{df[df.parsed_place.str.endswith('Indonesia')].tsunami.value_counts(normalize=True).loc[1,]:.2%}"""

'23.13%'

c. Get summary statistics for earthquakes in Nevada

In [ ]:
Nevada = df[df['place'].str.contains('Nevada')]

In [ ]:
Nevada.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,677.000000,15.000000,677.000000,677.000000,1.00,677.000000,677.000000,677.000000,6.770000e+02,677.0,677.0,6.770000e+02
mean,2.440000,0.166982,2.400000,154.029527,0.491728,2.84,12.608567,0.151909,10.688331,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166400,4.626013,68.769713,0.689560,NaN,9.890620,0.084742,19.252727,5.954070e+08,0.0,0.0,6.000267e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.054000,1.000000,97.670000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.113000,1.000000,149.550000,0.400000,2.84,9.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.234000,1.000000,200.470000,0.900000,2.84,16.000000,0.186700,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

d. Add a column to the dataframe indicating whether or not the earthquake happened in a country or US state that is on the Ring of Fire. Use Bolivia, Chile, Ecuador, Peru, Costa Rica, Guatemala, Mexico (be sure not to select New Mexico), Japan, Philippines, Indonesia, New Zealand, Antarctica (look for the Antarctic), Canada, Fiji, Alaska, Washington, California, Russia, Taiwan, Tonga, and the Kermadec Islands).

In [11]:
Ring_of_Fire = ['Bolivia','Chile', 'Ecuador', 'Peru', 'Costa Rica', 'Guatemala', 'Mexico'
'Japan', 'Philippines', 'Indonesia', 'New Zealand', 'Antarctica','Japan', 'Philippines',
'Indonesia', 'New Zealand', 'Antarctica', 'Canada', 'Fiji', 'Alaska', 'Washington',
'California', 'Russia', 'Taiwan', 'Tonga', 'Kermadec Islands']
df['Ring_of_Fire'] = df['place'].apply(lambda x:any(loc.lower() in str(x).lower() for loc in Ring_of_Fire))

or coding:

In [12]:
df['ring_of_fire'] = df.parsed_place.str.contains(r'|'.join([
    'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
    'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
    'New Zealand', 'Antarctic', 'Canada', 'Fiji',
    'Alaska', 'Washington', 'California', 'Russia',
    'Taiwan', 'Tonga', 'Kermadec Islands'
]))
df[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

e. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them

In [13]:
RoF_earthquakes = df[df['Ring_of_Fire'] == True]
print(RoF_earthquakes)

     alert  cdi      code                                             detail  \
6      NaN  NaN  20280432  https://earthquake.usgs.gov/fdsnws/event/1/que...
9      NaN  NaN  1000hbtn  https://earthquake.usgs.gov/fdsnws/event/1/que...
13     NaN  NaN  1000hbti  https://earthquake.usgs.gov/fdsnws/event/1/que...
15     NaN  NaN  20280430  https://earthquake.usgs.gov/fdsnws/event/1/que...
18     NaN  NaN  20280424  https://earthquake.usgs.gov/fdsnws/event/1/que...
...    ...  ...       ...                                                ...
9312   NaN  NaN  20257031  https://earthquake.usgs.gov/fdsnws/event/1/que...
9313   NaN  NaN  20257028  https://earthquake.usgs.gov/fdsnws/event/1/que...
9314   NaN  NaN  20257026  https://earthquake.usgs.gov/fdsnws/event/1/que...
9318   NaN  NaN  20257023  https://earthquake.usgs.gov/fdsnws/event/1/que...
9321   NaN  NaN  2000hjsq  https://earthquake.usgs.gov/fdsnws/event/1/que...

       dmin  felt    gap           ids  mag magType  ...  \
6       NaN   NaN    NaN  ,ak20280432,  1.7      ml  ...
9     3.191   NaN   37.0  ,us1000hbtn,  4.7      mb  ...
13    2.193   NaN  157.0  ,us1000hbti,  4.5      mb  ...
15      NaN   NaN    NaN  ,ak20280430,  2.0      ml  ...
18      NaN   NaN    NaN  ,ak20280424,  2.0      ml  ...
...     ...   ...    ...           ...  ...     ...  ...
9312    NaN   NaN    NaN  ,ak20257031,  2.5      ml  ...
9313    NaN   NaN    NaN  ,ak20257028,  1.5      ml  ...
9314    NaN   NaN    NaN  ,ak20257026,  2.0      ml  ...
9318    NaN   NaN    NaN  ,ak20257023,  1.1      ml  ...
9321  1.296   NaN   61.0  ,us2000hjsq,  4.3      mb  ...

                                             title tsunami        type  \
6             M 1.7 - 105km W of Talkeetna, Alaska       0  earthquake
9          M 4.7 - 219km SSE of Saparua, Indonesia       0  earthquake
13      M 4.5 - 120km SSW of Banda Aceh, Indonesia       0  earthquake
15    M 2.0 - 156km WNW of Haines Junction, Canada       0  earthquake
18            M 2.0 - 57km SSW of Kaktovik, Alaska       0  earthquake
...                                            ...     ...         ...
9312    M 2.5 - 134km NW of Arctic Village, Alaska       0  earthquake
9313          M 1.5 - 88km ESE of Whittier, Alaska       0  earthquake
9314   M 2.0 - 132km WNW of Arctic Village, Alaska       0  earthquake
9318               M 1.1 - 11km E of Healy, Alaska       0  earthquake
9321        M 4.3 - 19km NE of Cateel, Philippines       0  earthquake

                             types     tz        updated  \
6                ,geoserve,origin, -540.0  1539473596465
9     ,geoserve,origin,phase-data,  540.0  1539473712040
13    ,geoserve,origin,phase-data,  360.0  1539493516040
15               ,geoserve,origin, -480.0  1539473366902
18               ,geoserve,origin, -540.0  1539469037574
...                            ...    ...            ...
9312             ,geoserve,origin, -540.0  1537233354029
9313             ,geoserve,origin, -540.0  1537233353793
9314             ,geoserve,origin, -540.0  1537233252966
9318  ,geoserve,origin,phase-data, -540.0  1537294676737
9321  ,geoserve,origin,phase-data,  480.0  1538890521040

                                                    url parsed_place  \
6     https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
9     https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
13    https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
15    https://earthquake.usgs.gov/earthquakes/eventp...       Canada
18    https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
...                                                 ...          ...
9312  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
9313  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
9314  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
9318  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
9321  https://earthquake.usgs.gov/earthquakes/eventp...  Philippines

      Ring_of_Fire ring_of_fire
6             True         True
9             True         True
13            True         True
15            True         True
18            True         True
...            ...          ...
9312          True         True
9313          True         True
9314          True         True
9318          True         True
9321          True         True

[4410 rows x 29 columns]

or coding:

In [14]:
#Calculate the total number of events in the dataframe
df.type.value_counts()
#Filter the dataframe for earthquakes on the ring of fire and outside of the ring.
filtered_df = df[(df['ring_of_fire'] == True) & (df['type'] == 'earthquake')]
total_inside = df[(df['ring_of_fire'] == True) & (df['type'] == 'earthquake')].type.count()
total_outside = df[(df['ring_of_fire'] == False) & (df['type'] == 'earthquake')].type.count()
print('The total number of earthquakes in the Ring of Fire is: ', total_inside)
print('The total number of earthquakes outside the Ring of Fire is: ', total_outside)
#"An earthquake is caused by a sudden slip on a fault. The tectonic plates are always slowly moving,
#but they get stuck at their edges due to friction. When the stress on the edge overcomes the friction,
#there is an earthquake that releases energy in waves that travel through the earth's crust and cause
#the shaking that we feel."  - https://www.usgs.gov/faqs/what-earthquake-and-what-causes-them-happen
#Per the dictionary, an earthquake is a "shaking or trembling of the earth that is volcanic or tectonic in origin" - https://www.merriam-webster.com/dictionary/earthquake
#Other definitions, An earthquake (also known as a quake, tremor, big shake or temblor) is the shaking of the
#surface of the Earth resulting from a sudden release of energy in the Earth's lithosphere that creates seismic waves."
#https://en.wikipedia.org/wiki/Earthquake#:~:text=An%20earthquake%20%28also%20known%20as%20a%20quake%2C%20tremor,the%20Earth%20%27s%20lithosphere%20that%20creates%20seismic%20waves.

#Calulating the number of events that generate seismic activity.
#Defining any movement that records seismic activity
df['ring_of_fire'].value_counts()

The total number of earthquakes in the Ring of Fire is:  7004
The total number of earthquakes outside the Ring of Fire is:  2077

f. Find the tsunami count along the Ring of Fire.

In [20]:
RoF_tsunami = df[(df['Ring_of_Fire'] == True) & (df['tsunami'] == 1)]

In [23]:
print(RoF_tsunami)

      alert  cdi      code                                             detail  \
118   green  NaN  1000hbkz  https://earthquake.usgs.gov/fdsnws/event/1/que...
799   green  NaN  1000hacw  https://earthquake.usgs.gov/fdsnws/event/1/que...
1015  green  NaN  20275238  https://earthquake.usgs.gov/fdsnws/event/1/que...
1273  green  NaN  20274320  https://earthquake.usgs.gov/fdsnws/event/1/que...
1406    NaN  NaN  1000h8zg  https://earthquake.usgs.gov/fdsnws/event/1/que...
1698    NaN  4.3  1000h8gb  https://earthquake.usgs.gov/fdsnws/event/1/que...
1795  green  3.1  20272669  https://earthquake.usgs.gov/fdsnws/event/1/que...
2752  green  NaN  20270862  https://earthquake.usgs.gov/fdsnws/event/1/que...
3112    NaN  NaN  1000h68e  https://earthquake.usgs.gov/fdsnws/event/1/que...
3150    NaN  NaN  1000h66t  https://earthquake.usgs.gov/fdsnws/event/1/que...
3605    NaN  NaN  1000h5hb  https://earthquake.usgs.gov/fdsnws/event/1/que...
3609  green  NaN  1000h5h5  https://earthquake.usgs.gov/fdsnws/event/1/que...
3692  green  NaN  1000h5el  https://earthquake.usgs.gov/fdsnws/event/1/que...
3699  green  NaN  1000h5eg  https://earthquake.usgs.gov/fdsnws/event/1/que...
3707    NaN  NaN  1000h5eb  https://earthquake.usgs.gov/fdsnws/event/1/que...
3709    NaN  NaN  1000h5e3  https://earthquake.usgs.gov/fdsnws/event/1/que...
3714    NaN  NaN  1000h5du  https://earthquake.usgs.gov/fdsnws/event/1/que...
4027    NaN  2.0  1000h4vq  https://earthquake.usgs.gov/fdsnws/event/1/que...
4363  green  2.2  1000h4l1  https://earthquake.usgs.gov/fdsnws/event/1/que...
4827    NaN  NaN  1000h47j  https://earthquake.usgs.gov/fdsnws/event/1/que...
4888    NaN  NaN  1000h46e  https://earthquake.usgs.gov/fdsnws/event/1/que...
5054    NaN  NaN  1000h42g  https://earthquake.usgs.gov/fdsnws/event/1/que...
5146    NaN  NaN  1000h3v4  https://earthquake.usgs.gov/fdsnws/event/1/que...
5179    NaN  NaN  1000h3t2  https://earthquake.usgs.gov/fdsnws/event/1/que...
5195    NaN  NaN  1000h3sh  https://earthquake.usgs.gov/fdsnws/event/1/que...
5196  green  NaN  1000h3sd  https://earthquake.usgs.gov/fdsnws/event/1/que...
5214    NaN  NaN  1000h3rz  https://earthquake.usgs.gov/fdsnws/event/1/que...
5240    NaN  NaN  1000h3ra  https://earthquake.usgs.gov/fdsnws/event/1/que...
5244  green  NaN  1000h3r6  https://earthquake.usgs.gov/fdsnws/event/1/que...
5245    NaN  NaN  1000h3r7  https://earthquake.usgs.gov/fdsnws/event/1/que...
5250    NaN  NaN  1000h3r4  https://earthquake.usgs.gov/fdsnws/event/1/que...
5256  green  NaN  1000h3pn  https://earthquake.usgs.gov/fdsnws/event/1/que...
5258  green  3.8  1000h3rc  https://earthquake.usgs.gov/fdsnws/event/1/que...
5259  green  NaN  1000h3p8  https://earthquake.usgs.gov/fdsnws/event/1/que...
5263    red  8.4  1000h3p4  https://earthquake.usgs.gov/fdsnws/event/1/que...
5289    NaN  NaN  1000h3nd  https://earthquake.usgs.gov/fdsnws/event/1/que...
5321    NaN  NaN  1000h3n0  https://earthquake.usgs.gov/fdsnws/event/1/que...
5323  green  NaN  1000h3mf  https://earthquake.usgs.gov/fdsnws/event/1/que...
5790    NaN  NaN  1000h34s  https://earthquake.usgs.gov/fdsnws/event/1/que...
6004    NaN  3.1  1000h2u2  https://earthquake.usgs.gov/fdsnws/event/1/que...
6134    NaN  NaN  2000hk57  https://earthquake.usgs.gov/fdsnws/event/1/que...
8624    NaN  NaN  2000hhe6  https://earthquake.usgs.gov/fdsnws/event/1/que...
9133  green  2.2  20257361  https://earthquake.usgs.gov/fdsnws/event/1/que...

       dmin  felt   gap                                 ids  mag magType  ...  \
118   2.623   NaN  25.0  ,pt18286001,at00pgjb1a,us1000hbkz,  6.7     mww  ...
799   3.879   NaN  18.0  ,pt18283004,at00pgeomo,us1000hacw,  6.5     mww  ...
1015    NaN   NaN   NaN  ,at00pgddyl,ak20275238,us1000h9ts,  5.0      ml  ...
1273    NaN   NaN   NaN  ,ak20274320,at00pgblaz,us1000h975,  4.0      ml  ...
1406  2.132   NaN  79.0                        ,us1000h8zg,  5.1      mb  ...
1698  2.637  17.0  63.0                        ,us1000h8gb,  5.1     mww  ...
1795    NaN   2.0   NaN  ,ak20272669,at00pg8275,us1000h8de,  4.0      ml  ...
2752    NaN   NaN   NaN  ,ak20270862,at00pg2spo,us1000h6xg,  4.0      ml  ...
3112  2.745   NaN  80.0                        ,us1000h68e,  5.3      mb  ...
3150  2.710   NaN  79.0                        ,us1000h66t,  5.0     mww  ...
3605  2.596   NaN  90.0                        ,us1000h5hb,  5.0      mb  ...
3609  2.774   NaN  37.0                        ,us1000h5h5,  5.6     mww  ...
3692  2.738   NaN  49.0                        ,us1000h5el,  5.9     mww  ...
3699  2.715   NaN  46.0                        ,us1000h5eg,  6.0     mww  ...
3707  1.975   NaN  50.0                        ,us1000h5eb,  5.2     mww  ...
3709  2.714   NaN  59.0                        ,us1000h5e3,  5.4      mb  ...
3714  2.761   NaN  46.0                        ,us1000h5du,  5.0     mww  ...
4027  1.610   1.0  64.0                        ,us1000h4vq,  5.1     mww  ...
4363  3.728   1.0  23.0  ,at00pfv7ja,us1000h4l1,pt18273000,  6.7     mww  ...
4827  2.592   NaN  48.0                        ,us1000h47j,  5.1     mww  ...
4888  2.634   NaN  56.0                        ,us1000h46e,  5.1      mb  ...
5054  2.645   NaN  48.0                        ,us1000h42g,  5.0     mww  ...
5146  2.598   NaN  87.0                        ,us1000h3v4,  5.0      mb  ...
5179  1.601   NaN  35.0                        ,us1000h3t2,  5.4      mb  ...
5195  2.637   NaN  40.0                        ,us1000h3sh,  5.2      mb  ...
5196  1.517   NaN  21.0                        ,us1000h3sd,  5.7   ms_20  ...
5214  1.788   NaN  52.0                        ,us1000h3rz,  5.1      mb  ...
5240  2.695   NaN  52.0                        ,us1000h3ra,  5.2      mb  ...
5244  2.032   NaN  35.0                        ,us1000h3r6,  5.7      mb  ...
5245  1.850   NaN  77.0                        ,us1000h3r7,  5.1      mb  ...
5250  1.984   NaN  41.0                        ,us1000h3r4,  5.4      mb  ...
5256  2.309   NaN  40.0                        ,us1000h3pn,  5.8      mb  ...
5258  2.123   1.0  48.0                        ,us1000h3rc,  5.7      mb  ...
5259  1.504   NaN  41.0                        ,us1000h3p8,  5.8      mb  ...
5263  1.589  18.0  27.0             ,us1000h3p4,us1000h4p4,  7.5     mww  ...
5289  1.707   NaN  61.0                        ,us1000h3nd,  5.0      mb  ...
5321  1.517   NaN  72.0                        ,us1000h3n0,  5.4      mb  ...
5323  1.812   NaN  33.0                        ,us1000h3mf,  6.1     mww  ...
5790  1.083   NaN  94.0                        ,us1000h34s,  5.1      mb  ...
6004  1.099   2.0  31.0                        ,us1000h2u2,  5.1     mww  ...
6134  2.422   NaN  41.0                        ,us2000hk57,  5.0     mww  ...
8624  3.419   NaN  94.0                        ,us2000hhe6,  5.1      mb  ...
9133    NaN   1.0   NaN  ,ak20257361,at00pf94kc,us2000hgcj,  5.1      ml  ...

                                             title tsunami        type  \
118        M 6.7 - 262km NW of Ozernovskiy, Russia       1  earthquake
799     M 6.5 - 148km S of Severo-Kuril'sk, Russia       1  earthquake
1015      M 5.0 - 61km SSW of Chignik Lake, Alaska       1  earthquake
1273           M 4.0 - 71km SW of Kaktovik, Alaska       1  earthquake
1406             M 5.1 - 13km E of Palu, Indonesia       1  earthquake
1698       M 5.1 - 14km ENE of Sambelia, Indonesia       1  earthquake
1795            M 4.0 - 60km WNW of Valdez, Alaska       1  earthquake
2752          M 4.0 - 67km SSW of Kaktovik, Alaska       1  earthquake
3112        M 5.3 - 29km SSW of Nggongi, Indonesia       1  earthquake
3150     M 5.0 - 38km S of Nggongi Satu, Indonesia       1  earthquake
3605      M 5.0 - 50km WSW of Kasiguncu, Indonesia       1  earthquake
3609   M 5.6 - 33km SSW of Nggongi Satu, Indonesia       1  earthquake
3692        M 5.9 - 30km SSW of Nggongi, Indonesia       1  earthquake
3699     M 6.0 - 33km S of Nggongi Satu, Indonesia       1  earthquake
3707             M 5.2 - 25km N of Palu, Indonesia       1  earthquake
3709     M 5.4 - 31km S of Nggongi Satu, Indonesia       1  earthquake
3714   M 5.0 - 33km SSW of Nggongi Satu, Indonesia       1  earthquake
4027          M 5.1 - 101km NNW of Palu, Indonesia       1  earthquake
4363        M 6.7 - 263km NNE of Ndoi Island, Fiji       1  earthquake
4827        M 5.1 - 49km W of Kasiguncu, Indonesia       1  earthquake
4888        M 5.1 - 53km W of Kasiguncu, Indonesia       1  earthquake
5054      M 5.0 - 55km WSW of Kasiguncu, Indonesia       1  earthquake
5146           M 5.0 - 45km SSW of Palu, Indonesia       1  earthquake
5179          M 5.4 - 113km NNW of Palu, Indonesia       1  earthquake
5195             M 5.2 - 58km S of Palu, Indonesia       1  earthquake
5196            M 5.7 - 107km N of Palu, Indonesia       1  earthquake
5214             M 5.1 - 47km N of Palu, Indonesia       1  earthquake
5240           M 5.2 - 68km SSE of Palu, Indonesia       1  earthquake
5244           M 5.7 - 17km NNE of Palu, Indonesia       1  earthquake
5245             M 5.1 - 42km N of Palu, Indonesia       1  earthquake
5250             M 5.4 - 24km N of Palu, Indonesia       1  earthquake
5256           M 5.8 - 21km SSE of Palu, Indonesia       1  earthquake
5258             M 5.7 - 17km E of Palu, Indonesia       1  earthquake
5259             M 5.8 - 99km N of Palu, Indonesia       1  earthquake
5263             M 7.5 - 78km N of Palu, Indonesia       1  earthquake
5289             M 5.0 - 60km N of Palu, Indonesia       1  earthquake
5321           M 5.4 - 77km NNE of Palu, Indonesia       1  earthquake
5323           M 6.1 - 55km NNW of Palu, Indonesia       1  earthquake
5790        M 5.1 - 117km N of Saumlaki, Indonesia       1  earthquake
6004         M 5.1 - 19km WNW of Langsa, Indonesia       1  earthquake
6134        M 5.0 - 85km W of Manokwari, Indonesia       1  earthquake
8624  M 5.1 - 278km SE of Pondaguitan, Philippines       1  earthquake
9133          M 5.1 - 64km SSW of Kaktovik, Alaska       1  earthquake

                                                  types     tz        updated  \
118   ,geoserve,ground-failure,impact-link,losspager...  600.0  1539455437040
799   ,geoserve,ground-failure,impact-link,losspager...  600.0  1539224915040
1015  ,geoserve,ground-failure,impact-link,losspager... -540.0  1539213755442
1273  ,geoserve,impact-link,losspager,moment-tensor,... -540.0  1539101147040
1406                       ,geoserve,origin,phase-data,  480.0  1539037997040
1698                  ,dyfi,geoserve,origin,phase-data,  480.0  1539213200944
1795  ,dyfi,geoserve,impact-link,losspager,moment-te... -540.0  1538938071193
2752  ,geoserve,impact-link,losspager,moment-tensor,... -540.0  1539308895875
3112         ,geoserve,moment-tensor,origin,phase-data,  480.0  1538688306040
3150                       ,geoserve,origin,phase-data,  480.0  1538561863040
3605                       ,geoserve,origin,phase-data,  480.0  1538457427040
3609  ,geoserve,losspager,moment-tensor,origin,phase...  480.0  1538600570040
3692  ,geoserve,ground-failure,losspager,moment-tens...  480.0  1538457687574
3699  ,geoserve,ground-failure,losspager,moment-tens...  480.0  1538457423108
3707         ,geoserve,moment-tensor,origin,phase-data,  480.0  1538499097040
3709         ,geoserve,moment-tensor,origin,phase-data,  480.0  1538695468040
3714                       ,geoserve,origin,phase-data,  480.0  1538437120040
4027    ,dyfi,geoserve,moment-tensor,origin,phase-data,  480.0  1538500068040
4363  ,dyfi,geoserve,impact-link,losspager,moment-te... -720.0  1539348741510
4827         ,geoserve,moment-tensor,origin,phase-data,  480.0  1538501361040
4888                       ,geoserve,origin,phase-data,  480.0  1538207806040
5054                       ,geoserve,origin,phase-data,  480.0  1538170758040
5146                       ,geoserve,origin,phase-data,  480.0  1538151636040
5179                       ,geoserve,origin,phase-data,  480.0  1538916343040
5195                       ,geoserve,origin,phase-data,  480.0  1538895549040
5196    ,geoserve,losspager,origin,phase-data,shakemap,  480.0  1538895450840
5214                       ,geoserve,origin,phase-data,  480.0  1538138590040
5240                       ,geoserve,origin,phase-data,  480.0  1538133786040
5244    ,geoserve,losspager,origin,phase-data,shakemap,  480.0  1538139168395
5245                       ,geoserve,origin,phase-data,  480.0  1538132858040
5250                       ,geoserve,origin,phase-data,  480.0  1538132333040
5256    ,geoserve,losspager,origin,phase-data,shakemap,  480.0  1538137658671
5258  ,dyfi,geoserve,losspager,origin,phase-data,sha...  480.0  1538137146006
5259    ,geoserve,losspager,origin,phase-data,shakemap,  480.0  1538136994637
5263  ,dyfi,finite-fault,general-text,geoserve,groun...  480.0  1539123134531
5289                       ,geoserve,origin,phase-data,  480.0  1538123996040
5321                       ,geoserve,origin,phase-data,  480.0  1538120870040
5323  ,geoserve,ground-failure,losspager,moment-tens...  480.0  1538158590933
5790                       ,geoserve,origin,phase-data,  540.0  1538027116040
6004                  ,dyfi,geoserve,origin,phase-data,  420.0  1537989593711
6134                       ,geoserve,origin,phase-data,  540.0  1537955304040
8624                       ,geoserve,origin,phase-data,  540.0  1537411958040
9133  ,dyfi,geoserve,ground-failure,impact-link,loss... -540.0  1537394669040

                                                    url parsed_place  \
118   https://earthquake.usgs.gov/earthquakes/eventp...       Russia
799   https://earthquake.usgs.gov/earthquakes/eventp...       Russia
1015  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
1273  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
1406  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
1698  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
1795  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
2752  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska
3112  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3150  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3605  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3609  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3692  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3699  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3707  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3709  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
3714  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
4027  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
4363  https://earthquake.usgs.gov/earthquakes/eventp...         Fiji
4827  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
4888  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5054  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5146  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5179  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5195  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5196  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5214  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5240  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5244  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5245  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5250  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5256  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5258  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5259  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5263  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5289  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5321  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5323  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
5790  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
6004  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
6134  https://earthquake.usgs.gov/earthquakes/eventp...    Indonesia
8624  https://earthquake.usgs.gov/earthquakes/eventp...  Philippines
9133  https://earthquake.usgs.gov/earthquakes/eventp...       Alaska

      Ring_of_Fire ring_of_fire
118           True         True
799           True         True
1015          True         True
1273          True         True
1406          True         True
1698          True         True
1795          True         True
2752          True         True
3112          True         True
3150          True         True
3605          True         True
3609          True         True
3692          True         True
3699          True         True
3707          True         True
3709          True         True
3714          True         True
4027          True         True
4363          True         True
4827          True         True
4888          True         True
5054          True         True
5146          True         True
5179          True         True
5195          True         True
5196          True         True
5214          True         True
5240          True         True
5244          True         True
5245          True         True
5250          True         True
5256          True         True
5258          True         True
5259          True         True
5263          True         True
5289          True         True
5321          True         True
5323          True         True
5790          True         True
6004          True         True
6134          True         True
8624          True         True
9133          True         True

[43 rows x 29 columns]

or coding:

In [15]:
#.loc and .iloc are two important methods used for
#selecting data from a Pandas DataFrame or Series in Python.
#They allow you to access specific rows and columns of your data.

df.loc[df.ring_of_fire, 'tsunami'].sum()

np.int64(45)